update
upgrade

tap homebrew/binary
tap phinze/homebrew-cask

install boot2docker
install elixir
install erlang --devel
install docker
install hub
install mysql
install rust
install sbt
install vim --with-python3 --with-lua
install xctool
install brew-cask

cask install keyremap4macbook
cask install virtualbox
cask install vagrant
cask install sequel-pro

cleanup
